---
- name: Put all HBA entries togehter
  ansible.builtin.set_fact:
    postgresql_hba_entries: "{{ postgresql_hba_entries_default + postgresql_hba_entries_additional }}"
- name: Configure host based authentication (if entries are configured).
  ansible.builtin.template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgresql_config_path }}/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: "0600"
  become: true
  notify: Restart postgresql
  when: postgresql_hba_entries | length > 0
