---
- name: Configure host based authentication (if entries are configured).
  ansible.builtin.template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgresql_config_path }}/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: "0600"
  become: true
  notify: Restart postgresql
  when: postgresql_hba_entries | length > 0
- name: Configure listener to any interface
  become: true
  become_user: postgres
  ansible.builtin.lineinfile:
    path: "{{ postgresql_config_path }}/postgresql.conf"
    regexp: '^listen_addresses ='
    insertbefore: '^#listen_addresses'
    line: "listen_addresses = '*'"
  notify: Restart postgresql
