---
- name: Converge
  hosts: all
  remote_user: asudo
  gather_facts: true
  vars:
    postgresql_databases:
      - name: corpus # required; the rest are optional
        owner: corpus
    postgresql_users:
      - name: corpus # required; the rest are optional
        password: corpus
        db: corpus
    postgresql_hba_entries:
      - {type: local, database: all, user: postgres, auth_method: trust}
      - {type: local, database: all, user: all, auth_method: "{{ postgresql_auth_method }}"}
      - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: "{{ postgresql_auth_method }}"}
      - {type: host, database: all, user: all, address: '::1/128', auth_method: "{{ postgresql_auth_method }}"}
      - {type: host, database: corpus, user: corpus, address: 0.0.0.0/0, auth_method: "{{ postgresql_auth_method }}"}
  tasks:
    - name: Include ahu_services.postgresql
      ansible.builtin.include_role:
        name: ahu_services.postgresql
