---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "postgres-${image:-docker-rockylinux-systemd}-${tag:-9}-${psqlversion:-15.3}"
    image: "${namespace:-eniocarboni}/${image:-docker-rockylinux-systemd}:${tag:-9}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cgroupns: host
    privileged: true
    pre_build_image: true
    command: /usr/sbin/init
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        postgresql_version: "${psqlversion:-15.3}"
verifier:
  name: ansible
