---
dependency:
  name: galaxy
  options:
    requirements-file: "${MOLECULE_PROJECT_DIRECTORY}/requirements.yml"
driver:
  name: docker
platforms:
  - name: "postgres-${image:-docker-rockylinux-systemd}-${tag:-9}-${psqlversion:-17.6}"
    image: "${namespace:-geerlingguy}/${image:-docker-rockylinux9-ansible}:${tag:-latest}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run:rw,nosuid,size=64m
      - /run/lock:rw,nosuid,size=16m
      - /tmp:rw,nosuid,size=256m,mode=1777
    cgroupns: host
    privileged: true
    pre_build_image: true
    command: /sbin/init
    environment:
      container: docker
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /var/tmp/ansible-tmp
  inventory:
    group_vars:
      all:
        postgresql_version: "${psqlversion:-17.6}"
verifier:
  name: ansible
