---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "postgres-${image:-docker-rockylinux9-ansible}${TOX_ENVNAME}"
    image: "${namespace:-geerlingguy}/${image:-docker-rockylinux9-ansible}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cgroupns: host
    privileged: true
    pre_build_image: true
    command: /usr/sbin/init
provisioner:
  name: ansible
verifier:
  name: ansible
