---
- name: Prepare
  hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - name: Ensure Molecule test container is running
      delegate_to: localhost
      block:
        - name: Check container state
          ansible.builtin.command:
            argv:
              - docker
              - inspect
              - "-f={{'{{.State.Running}}'}}"
              - "{{ inventory_hostname }}"
          register: molecule_container_state
          changed_when: false
        - name: Start container when stopped
          ansible.builtin.command:
            argv:
              - docker
              - start
              - "{{ inventory_hostname }}"
          when: molecule_container_state.stdout.strip() != "true"
          changed_when: true
    - name: Wait for container connection
      ansible.builtin.wait_for_connection:
        timeout: 60
    - name: Ensure shared tmp directories exist
      ansible.builtin.raw: |
        set -euo pipefail
        install -d -m 01777 /tmp
        install -d -m 01777 /var/tmp/ansible-tmp
      changed_when: false

    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - sudo
          - shadow-utils

    - name: Create sudo user for tests
      ansible.builtin.user:
        name: asudo
        group: wheel
        password: "{{ 'asudo' | password_hash('sha512') }}"

    - name: Allow 'wheel' group to have passwordless sudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    - name: Allow asudo user to sudo without password
      ansible.builtin.copy:
        dest: /etc/sudoers.d/99-asudo
        content: "asudo ALL=(ALL) NOPASSWD: ALL\n"
        mode: '0440'
        owner: root
        group: root
        validate: 'visudo -cf %s'

    - name: Override sudo PAM config to avoid sssd dependency in tests
      ansible.builtin.copy:
        dest: /etc/pam.d/sudo
        owner: root
        group: root
        mode: '0644'
        content: |
          #%PAM-1.0
          auth       sufficient   pam_rootok.so
          auth       sufficient   pam_unix.so try_first_pass debug
          account    sufficient   pam_unix.so debug
          session    required     pam_limits.so
          session    required     pam_unix.so

    - name: Ensure NSS prefers files (avoid sssd dependency)
      ansible.builtin.copy:
        dest: /etc/nsswitch.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          passwd:     files
          shadow:     files
          group:      files
          sudoers:    files
          hosts:      files dns
          services:   files
          networks:   files
          protocols:  files
          rpc:        files
          ethers:     files
          netmasks:   files
          netgroup:   files
          bootparams: files
          automount:  files
          aliases:    files

    - name: Validate sudo setup (debugging, root context)
      block:
        - name: Inspect passwd entry for asudo
          ansible.builtin.command: getent passwd asudo
          register: postgresql_prepare_passwd
          changed_when: false
          failed_when: false
        - name: Inspect shadow entry for asudo
          ansible.builtin.command: getent shadow asudo
          register: postgresql_prepare_shadow
          changed_when: false
          failed_when: false
        - name: Inspect sudoers include for asudo
          ansible.builtin.command: stat /etc/sudoers.d/99-asudo
          register: postgresql_prepare_sudoers
          changed_when: false
          failed_when: false
        - name: Check passwordless sudo via su - asudo
          ansible.builtin.command: su - asudo -c "sudo -n true"
          register: postgresql_prepare_sudo_check
          changed_when: false
          failed_when: false
        - name: Show sudo diagnostics (prepare)
          ansible.builtin.debug:
            msg:
              passwd: "{{ postgresql_prepare_passwd.stdout | default('') }}"
              shadow: "{{ postgresql_prepare_shadow.stdout | default('') }}"
              sudoers: "{{ postgresql_prepare_sudoers.stdout | default('') }}"
              sudo_rc: "{{ postgresql_prepare_sudo_check.rc }}"

    - name: Collect PAM/NSS diagnostics (root context)
      block:
        - name: Show sudo PAM config
          ansible.builtin.command: cat /etc/pam.d/sudo
          register: postgresql_prepare_pam_sudo
          changed_when: false
          failed_when: false
        - name: Show system-auth PAM config
          ansible.builtin.command: cat /etc/pam.d/system-auth
          register: postgresql_prepare_pam_system_auth
          changed_when: false
          failed_when: false
        - name: Show nsswitch
          ansible.builtin.command: cat /etc/nsswitch.conf
          register: postgresql_prepare_nsswitch
          changed_when: false
          failed_when: false
        - name: Show sudo version details
          ansible.builtin.command: sudo -V
          register: postgresql_prepare_sudo_V
          changed_when: false
          failed_when: false
        - name: Check for sssd process
          ansible.builtin.command: pgrep -fl sssd
          register: postgresql_prepare_sssd
          changed_when: false
          failed_when: false
        - name: Show sudoers base file
          ansible.builtin.command: cat /etc/sudoers
          register: postgresql_prepare_sudoers_base
          changed_when: false
          failed_when: false
        - name: List sudoers.d entries
          ansible.builtin.command: ls -l /etc/sudoers.d
          register: postgresql_prepare_sudoers_d_ls
          changed_when: false
          failed_when: false
        - name: Show sudoers drop-in for asudo
          ansible.builtin.command: cat /etc/sudoers.d/99-asudo
          register: postgresql_prepare_sudoers_dropin
          changed_when: false
          failed_when: false
        - name: Tail PAM/secure logs
          ansible.builtin.command: tail -n 200 /var/log/secure
          register: postgresql_prepare_secure_log
          changed_when: false
          failed_when: false
        - name: Tail auth.log (if present)
          ansible.builtin.command: tail -n 200 /var/log/auth.log
          register: postgresql_prepare_auth_log
          changed_when: false
          failed_when: false
        - name: Show PAM/NSS diagnostics
          ansible.builtin.debug:
            msg:
              pam_sudo: "{{ postgresql_prepare_pam_sudo.stdout | default('') }}"
              pam_system_auth: "{{ postgresql_prepare_pam_system_auth.stdout | default('') }}"
              nsswitch: "{{ postgresql_prepare_nsswitch.stdout | default('') }}"
              sudo_V: "{{ postgresql_prepare_sudo_V.stdout | default('') }}"
              sssd: "{{ postgresql_prepare_sssd.stdout | default('') }}"
              sudoers_base: "{{ postgresql_prepare_sudoers_base.stdout | default('') }}"
              sudoers_d_ls: "{{ postgresql_prepare_sudoers_d_ls.stdout | default('') }}"
              sudoers_dropin: "{{ postgresql_prepare_sudoers_dropin.stdout | default('') }}"
              secure_log: "{{ postgresql_prepare_secure_log.stdout | default('') }}"
              auth_log: "{{ postgresql_prepare_auth_log.stdout | default('') }}"
