---
- name: Prepare
  hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - name: Ensure shared tmp directories exist
      ansible.builtin.raw: |
        set -euo pipefail
        install -d -m 01777 /tmp
        install -d -m 01777 /var/tmp/ansible-tmp
      changed_when: false

    - name: Install required packages
      ansible.builtin.dnf:
        name: sudo

    - name: Create sudo user for tests
      ansible.builtin.user:
        name: asudo
        group: wheel

    - name: Allow 'wheel' group to have passwordless sudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
