---
- name: Prepare
  hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - name: Install required packages
      ansible.builtin.dnf:
        name: sudo
    - name: Create sudo user
      ansible.builtin.user:
        name: asudo
        group: wheel
    - name: Ensure shared Ansible tmp exists
      ansible.builtin.file:
        path: /tmp/ansible-tmp
        state: directory
        mode: "01777"
    - name: Show tmp permissions for debugging
      ansible.builtin.command: ls -ld /tmp /tmp/ansible-tmp
      register: tmp_ls
      changed_when: false
      failed_when: tmp_ls.rc != 0
    - name: Allow 'wheel' group to have passwordless sudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
