---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get desired version installed from environment
      ansible.builtin.set_fact:
        psql_version: "{{ lookup('ansible.builtin.env', 'psqlversion', default='17.6') }}"
    - name: Set major version variables accordingly
      ansible.builtin.set_fact:
        psql_version_major: "{{ psql_version | split('.') | first }}"
    - name: Set server name accordingly
      ansible.builtin.set_fact:
        psql_server_name: "postgresql{{ psql_version_major }}"
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Check PostgreSQL packages are installed
      ansible.builtin.assert:
        that:
          - ansible_facts.packages[psql_server_name][0].version == psql_version
          - ansible_facts.packages[psql_server_name + "-server"][0].version == psql_version
    - name: Check if PostgreSQL database is initialized
      ansible.builtin.stat:
        path: "/var/lib/pgsql/{{ psql_version_major }}/data/PG_VERSION"
      register: pgdata_dir_version
    - name: Check postgresql DB was initialized
      ansible.builtin.assert:
        that: pgdata_dir_version.stat.exists
    - name: Collect facts about system services
      ansible.builtin.service_facts:
      register: services_state
    - name: Check postgresql is running
      ansible.builtin.assert:
        that: services_state.ansible_facts.services['postgresql-' + psql_version_major + '.service'].state == 'running'
    - name: Gather info about PostgreSQL users and databases
      become: true
      become_user: postgres
      community.postgresql.postgresql_info:
        filter:
          - "databases"
          - "roles"
          - "version"
          - "settings"
      register: postgres_info
    - name: Check database "corpus" exists
      ansible.builtin.assert:
        that:
          - '"corpus" in postgres_info.databases'
          - postgres_info.databases.corpus.owner == "corpus"
    - name: Check role "corpus" exists
      ansible.builtin.assert:
        that:
          - '"corpus" in postgres_info.roles'
    - name: Check version for PostgreSQL
      ansible.builtin.assert:
        that:
          - postgres_info.version.full == psql_version
    - name: Ensure pg_stat_statements is preloaded
      ansible.builtin.assert:
        that:
          - "'pg_stat_statements' in (postgres_info.settings.shared_preload_libraries.setting | default(''))"
        fail_msg: "pg_stat_statements missing from shared_preload_libraries"
        success_msg: "pg_stat_statements present in shared_preload_libraries"
    - name: Check content of the configuration file
      ansible.builtin.slurp:
        src: /var/lib/pgsql/{{ psql_version_major }}/data/postgresql.conf
      register: pgsql_conf
    - name: Assert file content
      ansible.builtin.assert:
        that:
          - "\"listen_addresses = '*'\" in (pgsql_conf['content'] | b64decode)"
        fail_msg: "'listen_addresses = '*' setting is missing in postgresql.conf"
        success_msg: "'listen_addresses = '*' setting is present in postgresql.conf"
    - name: Check pg_stat_statements extension exists in postgres database
      become: true
      become_user: postgres
      community.postgresql.postgresql_query:
        db: postgres
        query: "SELECT extname FROM pg_extension WHERE extname = 'pg_stat_statements'"
      register: pg_stat_statements_extension
    - name: Assert pg_stat_statements extension exists
      ansible.builtin.assert:
        that:
          - (pg_stat_statements_extension.query_result | length) == 1
        fail_msg: "pg_stat_statements extension missing from postgres database"
        success_msg: "pg_stat_statements extension present in postgres database"
