---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Check PostgreSQL packages are installed
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['postgresql15'][0].version == '15.3'
          - ansible_facts.packages['postgresql15-server'][0].version == '15.3'
    - name: Check if PostgreSQL database is initialized
      ansible.builtin.stat:
        path: "/var/lib/pgsql/15/data/PG_VERSION"
      register: pgdata_dir_version
    - name: Check postgresql-15 DB was initialized
      ansible.builtin.assert:
        that: pgdata_dir_version.stat.exists
    - name: Collect facts about system services
      ansible.builtin.service_facts:
      register: services_state
    - name: Check postgresql-15 is running
      ansible.builtin.assert:
        that: services_state.ansible_facts.services['postgresql-15.service'].state == 'running'
    - name: Gather info about PostgreSQL users and databases
      become: true
      become_user: postgres
      community.postgresql.postgresql_info:
        filter:
          - "databases"
          - "roles"
          - "version"
      register: postgres_info
    - name: Check database "corpus" exists
      ansible.builtin.assert:
        that:
          - '"corpus" in postgres_info.databases'
          - postgres_info.databases.corpus.owner == "corpus"
    - name: Check role "corpus" exists
      ansible.builtin.assert:
        that:
          - '"corpus" in postgres_info.roles'
    - name: Check version for PostgreSQL
      ansible.builtin.assert:
        that:
          - postgres_info.version.full == "15.3"
